/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package my.userrepo;

import javax.swing.JFrame;

public class DodajStudentaPanel extends javax.swing.JPanel {

    private static final String[] OCENY = new String[] {"","2", "3","4","5"};
    private DodajStudentaFrame addUserFrame;
    /**
     * Creates new form AddUser
     */
    public DodajStudentaPanel(DodajStudentaFrame addUserFrame) {
        this.addUserFrame = addUserFrame;
        initComponents();
    }

    DodajStudentaPanel() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        imieTextField = new javax.swing.JTextField();
        nazwiskoTextField = new javax.swing.JTextField();
        telefonTextField = new javax.swing.JTextField();
        adresTextField = new javax.swing.JTextField();
        imieLablel = new javax.swing.JLabel();
        nazwiskoLabel = new javax.swing.JLabel();
        telefonLabel = new javax.swing.JLabel();
        adresLabel = new javax.swing.JLabel();
        kolokwium1jComboBox = new javax.swing.JComboBox();
        kolokwium2ComboBox = new javax.swing.JComboBox();
        kolokwium3ComboBox = new javax.swing.JComboBox();
        praktyczneComboBox = new javax.swing.JComboBox();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        zapiszButton = new javax.swing.JButton();

        imieTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                imieTextFieldActionPerformed(evt);
            }
        });

        nazwiskoTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nazwiskoTextFieldActionPerformed(evt);
            }
        });

        imieLablel.setText("Imie");

        nazwiskoLabel.setText("Nazwisko");

        telefonLabel.setText("Telefon");

        adresLabel.setText("Adres");

        kolokwium1jComboBox.setModel(new javax.swing.DefaultComboBoxModel(OCENY));

        kolokwium2ComboBox.setModel(new javax.swing.DefaultComboBoxModel(OCENY));

        kolokwium3ComboBox.setModel(new javax.swing.DefaultComboBoxModel(OCENY));

        praktyczneComboBox.setModel(new javax.swing.DefaultComboBoxModel(OCENY));

        jLabel5.setText("Kolokwium 1");

        jLabel6.setText("Kolokwium 2");

        jLabel7.setText("Kolokwium 3");

        jLabel8.setText("Zadanie praktyczne");

        zapiszButton.setText("Zapisz");
        zapiszButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                zapiszButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(nazwiskoTextField)
                    .addComponent(imieTextField)
                    .addComponent(telefonTextField)
                    .addComponent(adresTextField)
                    .addComponent(imieLablel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(nazwiskoLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(telefonLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(adresLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(zapiszButton, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(kolokwium1jComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(kolokwium3ComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(kolokwium2ComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(praktyczneComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 10, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(imieLablel)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(imieTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(nazwiskoLabel)
                        .addGap(5, 5, 5)
                        .addComponent(nazwiskoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(1, 1, 1)
                        .addComponent(telefonLabel)
                        .addGap(3, 3, 3)
                        .addComponent(telefonTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(3, 3, 3)
                        .addComponent(adresLabel)
                        .addGap(1, 1, 1)
                        .addComponent(adresTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(kolokwium1jComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(kolokwium2ComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(kolokwium3ComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(praktyczneComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8))))
                .addGap(14, 14, 14)
                .addComponent(zapiszButton, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void imieTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_imieTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_imieTextFieldActionPerformed

    private void nazwiskoTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nazwiskoTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nazwiskoTextFieldActionPerformed

    private void zapiszButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_zapiszButtonActionPerformed
        addUserFrame.showBackToMein();
        addUserFrame.setVisible(false);
        addUserFrame.dispose();
    }//GEN-LAST:event_zapiszButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel adresLabel;
    private javax.swing.JTextField adresTextField;
    private javax.swing.JLabel imieLablel;
    private javax.swing.JTextField imieTextField;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JComboBox kolokwium1jComboBox;
    private javax.swing.JComboBox kolokwium2ComboBox;
    private javax.swing.JComboBox kolokwium3ComboBox;
    private javax.swing.JLabel nazwiskoLabel;
    private javax.swing.JTextField nazwiskoTextField;
    private javax.swing.JComboBox praktyczneComboBox;
    private javax.swing.JLabel telefonLabel;
    private javax.swing.JTextField telefonTextField;
    private javax.swing.JButton zapiszButton;
    // End of variables declaration//GEN-END:variables
}
