/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package my.userrepo;

public class WyswietlPanel extends javax.swing.JPanel {

    WyswietlFrame mainFrame;
    /**
     * Creates new form WyswietlPanel
     */
    public WyswietlPanel(WyswietlFrame mainFrame) {
        this.mainFrame = mainFrame;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        wszytskoRadioButton = new javax.swing.JRadioButton();
        zaliczoneRadioButton = new javax.swing.JRadioButton();
        nieZalicozneRadioButton3 = new javax.swing.JRadioButton();
        wyswietlLabel = new javax.swing.JLabel();
        szukajTextField = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        wyswietlButton = new javax.swing.JButton();

        wszytskoRadioButton.setText("wszystkich");

        zaliczoneRadioButton.setText("zaliczonych");

        nieZalicozneRadioButton3.setText("niezaliczone");

        wyswietlLabel.setText("Wyswietl:");

        szukajTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                szukajTextFieldActionPerformed(evt);
            }
        });

        jLabel1.setText("Imię lub Nazwisko");

        wyswietlButton.setText("wyswietl");
        wyswietlButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                wyswietlButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(30, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(nieZalicozneRadioButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(zaliczoneRadioButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(wszytskoRadioButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(wyswietlLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(szukajTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(wyswietlButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(wyswietlLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(wszytskoRadioButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(zaliczoneRadioButton)
                .addGap(7, 7, 7)
                .addComponent(nieZalicozneRadioButton3)
                .addGap(6, 6, 6)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(szukajTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(wyswietlButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void szukajTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_szukajTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_szukajTextFieldActionPerformed

    private void wyswietlButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_wyswietlButtonActionPerformed
        mainFrame.showBackToMein();
        mainFrame.setVisible(false);
        mainFrame.dispose();
    }//GEN-LAST:event_wyswietlButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JRadioButton nieZalicozneRadioButton3;
    private javax.swing.JTextField szukajTextField;
    private javax.swing.JRadioButton wszytskoRadioButton;
    private javax.swing.JButton wyswietlButton;
    private javax.swing.JLabel wyswietlLabel;
    private javax.swing.JRadioButton zaliczoneRadioButton;
    // End of variables declaration//GEN-END:variables
}
